<?php

use Illuminate\Database\Seeder;

class tb_MaterialSeeder extends Seeder
{
	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run()
	{
		DB::table('tb_material')->insert([
			[
				'proj_id' => 1,
				'mt_id' => 3,
				'pp_proc_id' => 5,
				'pr_proc_id' => 9,
				'pp_stat_id' => 4,
				'pr_stat_id' => 4,
				'mat_spec' => '10m x 10m',
				'mat_thick' => 1.5,
				'mat_no' => 1,
				'purchased_at' => date("Y-m-d H:i:s", mt_rand(strtotime("2017-10-01"),strtotime("2017-12-30"))),
				'arrived_at' => date("Y-m-d H:i:s", mt_rand(strtotime("2018-01-01"),strtotime("2018-02-28"))),
				'created_at' => date("Y-m-d H:i:s", mt_rand(strtotime("2017-10-01"),strtotime("2017-12-30"))),
			],
			[
				'proj_id' => 1,
				'mt_id' => 45,
				'pp_proc_id' => 5,
				'pr_proc_id' => 9,
				'pp_stat_id' => 4,
				'pr_stat_id' => 4,
				'mat_spec' => '10m x 10m',
				'mat_thick' => 1.5,
				'mat_no' => 1,
				'purchased_at' => date("Y-m-d H:i:s", mt_rand(strtotime("2017-10-01"),strtotime("2017-12-30"))),
				'arrived_at' => date("Y-m-d H:i:s", mt_rand(strtotime("2018-01-01"),strtotime("2018-02-28"))),
				'created_at' => date("Y-m-d H:i:s", mt_rand(strtotime("2017-10-01"),strtotime("2017-12-30"))),
			],
			[
				'proj_id' => 1,
				'mt_id' => 59,
				'pp_proc_id' => 5,
				'pr_proc_id' => 9,
				'pp_stat_id' => 4,
				'pr_stat_id' => 4,
				'mat_spec' => '10m x 10m',
				'mat_thick' => 1.5,
				'mat_no' => 1,
				'purchased_at' => date("Y-m-d H:i:s", mt_rand(strtotime("2017-10-01"),strtotime("2017-12-30"))),
				'arrived_at' => date("Y-m-d H:i:s", mt_rand(strtotime("2018-01-01"),strtotime("2018-02-28"))),
				'created_at' => date("Y-m-d H:i:s", mt_rand(strtotime("2017-10-01"),strtotime("2017-12-30"))),
			],
			[
				'proj_id' => 1,
				'mt_id' => 30,
				'pp_proc_id' => 5,
				'pr_proc_id' => 9,
				'pp_stat_id' => 4,
				'pr_stat_id' => 4,
				'mat_spec' => '10m x 10m',
				'mat_thick' => 1.5,
				'mat_no' => 1,
				'purchased_at' => date("Y-m-d H:i:s", mt_rand(strtotime("2017-10-01"),strtotime("2017-12-30"))),
				'arrived_at' => date("Y-m-d H:i:s", mt_rand(strtotime("2018-01-01"),strtotime("2018-02-28"))),
				'created_at' => date("Y-m-d H:i:s", mt_rand(strtotime("2017-10-01"),strtotime("2017-12-30"))),
			],
		]);

		// project 1
		DB::table('tb_progress')->insert([
			[
				'proj_id' => 1,
				'user_id' => 2,
				'proc_id' => 2,
				'mat_id'   => 0,
				'prog_remark' => 'Project Tag Boat has moved to the Pra Preparation Process by PPC 1',
				'created_at' => date("Y-m-d H:i:s", mt_rand(strtotime("2017-10-01"),strtotime("2017-11-30"))),
			],
			[
				'proj_id' => 1,
				'user_id' => 2,
				'proc_id' => 3,
				'mat_id'   => 1,
				'prog_remark' => "Material has been purchased by PPC 1",
				'created_at' => date("Y-m-d H:i:s", mt_rand(strtotime("2017-10-01"),strtotime("2017-11-30"))),
			],
			[
				'proj_id' => 1,
				'user_id' => 2,
				'proc_id' => 3,
				'mat_id'   => 2,
				'prog_remark' => "Material has been purchased by PPC 1",
				'created_at' => date("Y-m-d H:i:s", mt_rand(strtotime("2017-10-01"),strtotime("2017-11-30"))),
			],
			[
				'proj_id' => 1,
				'user_id' => 2,
				'proc_id' => 3,
				'mat_id'   => 3,
				'prog_remark' => "Material has been purchased by PPC 1",
				'created_at' => date("Y-m-d H:i:s", mt_rand(strtotime("2017-10-01"),strtotime("2017-11-30"))),
			],
			[
				'proj_id' => 1,
				'user_id' => 2,
				'proc_id' => 3,
				'mat_id'   => 4,
				'prog_remark' => "Material has been purchased by PPC 1",
				'created_at' => date("Y-m-d H:i:s", mt_rand(strtotime("2017-10-01"),strtotime("2017-11-30"))),
			],
			[
				'proj_id' => 1,
				'user_id' => 2,
				'proc_id' => 4,
				'mat_id'   => 1,
				'prog_remark' => "Material arrived by PPC 1",
				'created_at' => date("Y-m-d H:i:s", mt_rand(strtotime("2017-11-01"),strtotime("2017-12-30"))),
			],
			[
				'proj_id' => 1,
				'user_id' => 2,
				'proc_id' => 4,
				'mat_id'   => 2,
				'prog_remark' => "Material arrived by PPC 1",
				'created_at' => date("Y-m-d H:i:s", mt_rand(strtotime("2017-11-01"),strtotime("2017-12-30"))),
			],
			[
				'proj_id' => 1,
				'user_id' => 2,
				'proc_id' => 4,
				'mat_id'   => 3,
				'prog_remark' => "Material arrived by PPC 1",
				'created_at' => date("Y-m-d H:i:s", mt_rand(strtotime("2017-11-01"),strtotime("2017-12-30"))),
			],
			[
				'proj_id' => 1,
				'user_id' => 2,
				'proc_id' => 4,
				'mat_id'   => 4,
				'prog_remark' => "Material arrived by PPC 1",
				'created_at' => date("Y-m-d H:i:s", mt_rand(strtotime("2017-11-01"),strtotime("2017-12-30"))),
			],
			[
				'proj_id' => 1,
				'user_id' => 2,
				'proc_id' => 5,
				'mat_id'   => 1,
				'prog_remark' => 'Material has moved to the Identification sub process by PPC 1',
				'created_at' => date("Y-m-d H:i:s", mt_rand(strtotime("2017-12-01"),strtotime("2018-01-30"))),
			],
			[
				'proj_id' => 1,
				'user_id' => 2,
				'proc_id' => 5,
				'mat_id'   => 2,
				'prog_remark' => 'Material has moved to the Identification sub process by PPC 1',
				'created_at' => date("Y-m-d H:i:s", mt_rand(strtotime("2017-12-01"),strtotime("2018-01-30"))),
			],
			[
				'proj_id' => 1,
				'user_id' => 2,
				'proc_id' => 5,
				'mat_id'   => 3,
				'prog_remark' => 'Material has moved to the Identification sub process by PPC 1',
				'created_at' => date("Y-m-d H:i:s", mt_rand(strtotime("2017-12-01"),strtotime("2018-01-30"))),
			],
			[
				'proj_id' => 1,
				'user_id' => 2,
				'proc_id' => 5,
				'mat_id'   => 4,
				'prog_remark' => 'Material has moved to the Identification sub process by PPC 1',
				'created_at' => date("Y-m-d H:i:s", mt_rand(strtotime("2017-12-01"),strtotime("2018-01-30"))),
			],
			[
				'proj_id' => 1,
				'user_id' => 2,
				'proc_id' => 6,
				'mat_id'   => 1,
				'prog_remark' => 'Material has moved to the Preparation Process by PPC 1',
				'created_at' => date("Y-m-d H:i:s", mt_rand(strtotime("2018-01-01"),strtotime("2018-02-28"))),
			],
			[
				'proj_id' => 1,
				'user_id' => 2,
				'proc_id' => 6,
				'mat_id'   => 2,
				'prog_remark' => 'Material has moved to the Preparation Process by PPC 1',
				'created_at' => date("Y-m-d H:i:s", mt_rand(strtotime("2018-01-01"),strtotime("2018-02-28"))),
			],
			[
				'proj_id' => 1,
				'user_id' => 2,
				'proc_id' => 6,
				'mat_id'   => 3,
				'prog_remark' => 'Material has moved to the Preparation Process by PPC 1',
				'created_at' => date("Y-m-d H:i:s", mt_rand(strtotime("2018-01-01"),strtotime("2018-02-28"))),
			],
			[
				'proj_id' => 1,
				'user_id' => 2,
				'proc_id' => 6,
				'mat_id'   => 4,
				'prog_remark' => 'Material has moved to the Preparation Process by PPC 1',
				'created_at' => date("Y-m-d H:i:s", mt_rand(strtotime("2018-01-01"),strtotime("2018-02-28"))),
			],
			[
				'proj_id' => 1,
				'user_id' => 2,
				'proc_id' => 7,
				'mat_id'   => 1,
				'prog_remark' => 'Material has moved to the straightening sub process by PPC 1',
				'created_at' => date("Y-m-d H:i:s", mt_rand(strtotime("2018-01-01"),strtotime("2018-02-28"))),
			],
			[
				'proj_id' => 1,
				'user_id' => 2,
				'proc_id' => 7,
				'mat_id'   => 2,
				'prog_remark' => 'Material has moved to the straightening sub process by PPC 1',
				'created_at' => date("Y-m-d H:i:s", mt_rand(strtotime("2018-01-01"),strtotime("2018-02-28"))),
			],
			[
				'proj_id' => 1,
				'user_id' => 2,
				'proc_id' => 7,
				'mat_id'   => 3,
				'prog_remark' => 'Material has moved to the straightening sub process by PPC 1',
				'created_at' => date("Y-m-d H:i:s", mt_rand(strtotime("2018-01-01"),strtotime("2018-02-28"))),
			],
			[
				'proj_id' => 1,
				'user_id' => 2,
				'proc_id' => 7,
				'mat_id'   => 4,
				'prog_remark' => 'Material has moved to the straightening sub process by PPC 1',
				'created_at' => date("Y-m-d H:i:s", mt_rand(strtotime("2018-01-01"),strtotime("2018-02-28"))),
			],
			[
				'proj_id' => 1,
				'user_id' => 2,
				'proc_id' => 8,
				'mat_id'   => 1,
				'prog_remark' => 'Material has moved to the blasting sub process by PPC 1',
				'created_at' => date("Y-m-d H:i:s", mt_rand(strtotime("2018-02-01"),strtotime("2018-03-30"))),
			],
			[
				'proj_id' => 1,
				'user_id' => 2,
				'proc_id' => 8,
				'mat_id'   => 2,
				'prog_remark' => 'Material has moved to the blasting sub process by PPC 1',
				'created_at' => date("Y-m-d H:i:s", mt_rand(strtotime("2018-02-01"),strtotime("2018-03-30"))),
			],
			[
				'proj_id' => 1,
				'user_id' => 2,
				'proc_id' => 8,
				'mat_id'   => 3,
				'prog_remark' => 'Material has moved to the blasting sub process by PPC 1',
				'created_at' => date("Y-m-d H:i:s", mt_rand(strtotime("2018-02-01"),strtotime("2018-03-30"))),
			],
			[
				'proj_id' => 1,
				'user_id' => 2,
				'proc_id' => 8,
				'mat_id'   => 4,
				'prog_remark' => 'Material has moved to the blasting sub process by PPC 1',
				'created_at' => date("Y-m-d H:i:s", mt_rand(strtotime("2018-02-01"),strtotime("2018-03-30"))),
			],
			[
				'proj_id' => 1,
				'user_id' => 2,
				'proc_id' => 9,
				'mat_id'   => 1,
				'prog_remark' => 'Material has moved to the primering sub process by PPC 1',
				'created_at' => date("Y-m-d H:i:s", mt_rand(strtotime("2018-03-01"),strtotime("2018-04-30"))),
			],
			[
				'proj_id' => 1,
				'user_id' => 2,
				'proc_id' => 9,
				'mat_id'   => 2,
				'prog_remark' => 'Material has moved to the primering sub process by PPC 1',
				'created_at' => date("Y-m-d H:i:s", mt_rand(strtotime("2018-03-01"),strtotime("2018-04-30"))),
			],
			[
				'proj_id' => 1,
				'user_id' => 2,
				'proc_id' => 9,
				'mat_id'   => 3,
				'prog_remark' => 'Material has moved to the primering sub process by PPC 1',
				'created_at' => date("Y-m-d H:i:s", mt_rand(strtotime("2018-03-01"),strtotime("2018-04-30"))),
			],
			[
				'proj_id' => 1,
				'user_id' => 2,
				'proc_id' => 9,
				'mat_id'   => 4,
				'prog_remark' => 'Material has moved to the primering sub process by PPC 1',
				'created_at' => date("Y-m-d H:i:s", mt_rand(strtotime("2018-03-01"),strtotime("2018-04-30"))),
			],
		]);
	}
}
