<?php

use Illuminate\Database\Seeder;

class tb_PiecepartSeeder extends Seeder
{
	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run()
	{
		DB::table('tb_piecepart')->insert([
			[
				'proj_id' => 1,
				'mat_id'	=> 1,
				'pan_id'	=> 1,
				'proc_id' => 13,
				'stat_id' => 4,
				'pp_name'	=> 'pp 1',
				'pp_no'		=> 1,
				'created_at' => date("Y-m-d H:i:s", mt_rand(strtotime("2018-05-01"),strtotime("2018-06-30"))),
			],
			[
				'proj_id' => 1,
				'mat_id'	=> 1,
				'pan_id'	=> 2,
				'proc_id' => 13,
				'stat_id' => 4,
				'pp_name'	=> 'pp 2',
				'pp_no'		=> 2,
				'created_at' => date("Y-m-d H:i:s", mt_rand(strtotime("2018-05-01"),strtotime("2018-06-30"))),
			],
			[
				'proj_id' => 1,
				'mat_id'	=> 1,
				'pan_id'	=> 1,
				'proc_id' => 13,
				'stat_id' => 4,
				'pp_name'	=> 'pp 3',
				'pp_no'		=> 3,
				'created_at' => date("Y-m-d H:i:s", mt_rand(strtotime("2018-05-01"),strtotime("2018-06-30"))),
			],
			[
				'proj_id' => 1,
				'mat_id'	=> 2,
				'pan_id'	=> 2,
				'proc_id' => 13,
				'stat_id' => 4,
				'pp_name'	=> 'pp 4',
				'pp_no'		=> 4,
				'created_at' => date("Y-m-d H:i:s", mt_rand(strtotime("2018-05-01"),strtotime("2018-06-30"))),
			],
			[
				'proj_id' => 1,
				'mat_id'	=> 2,
				'pan_id'	=> 1,
				'proc_id' => 13,
				'stat_id' => 4,
				'pp_name'	=> 'pp 5',
				'pp_no'		=> 5,
				'created_at' => date("Y-m-d H:i:s", mt_rand(strtotime("2018-05-01"),strtotime("2018-06-30"))),
			],
			[
				'proj_id' => 1,
				'mat_id'	=> 3,
				'pan_id'	=> 3,
				'proc_id' => 13,
				'stat_id' => 4,
				'pp_name'	=> 'pp 6',
				'pp_no'		=> 6,
				'created_at' => date("Y-m-d H:i:s", mt_rand(strtotime("2018-05-01"),strtotime("2018-06-30"))),
			],
			[
				'proj_id' => 1,
				'mat_id'	=> 3,
				'pan_id'	=> 4,
				'proc_id' => 13,
				'stat_id' => 4,
				'pp_name'	=> 'pp 7',
				'pp_no'		=> 7,
				'created_at' => date("Y-m-d H:i:s", mt_rand(strtotime("2018-05-01"),strtotime("2018-06-30"))),
			],
			[
				'proj_id' => 1,
				'mat_id'	=> 4,
				'pan_id'	=> 4,
				'proc_id' => 13,
				'stat_id' => 4,
				'pp_name'	=> 'pp 8',
				'pp_no'		=> 8,
				'created_at' => date("Y-m-d H:i:s", mt_rand(strtotime("2018-05-01"),strtotime("2018-06-30"))),
			],
		]);

		// PROGREESS PIECEPART PROJECT 1
		DB::table('tb_progress')->insert([
			[
				'proj_id' => 1,
				'user_id' => 1,
				'proc_id' => 10,
				'mat_id' => 1,
				'prog_remark' => 'Material has moved to the Fabrication process by PPC 1',
				'created_at' => date("Y-m-d H:i:s", mt_rand(strtotime("2018-05-01"),strtotime("2018-06-30"))),
			],
			[
				'proj_id' => 1,
				'user_id' => 1,
				'proc_id' => 10,
				'mat_id' => 2,
				'prog_remark' => 'Material has moved to the Fabrication process by PPC 1',
				'created_at' => date("Y-m-d H:i:s", mt_rand(strtotime("2018-05-01"),strtotime("2018-06-30"))),
			],
			[
				'proj_id' => 1,
				'user_id' => 1,
				'proc_id' => 10,
				'mat_id' => 3,
				'prog_remark' => 'Material has moved to the Fabrication process by PPC 1',
				'created_at' => date("Y-m-d H:i:s", mt_rand(strtotime("2018-05-01"),strtotime("2018-06-30"))),
			],
		]);
		DB::table('tb_progress')->insert([
			[
				'proj_id' => 1,
				'user_id' => 1,
				'proc_id' => 11,
				'mat_id' => 1,
				'pp_id'	=> 1,
				'prog_remark' => 'Material has moved to the marking subprocess by PPC 1',
				'created_at' => date("Y-m-d H:i:s", mt_rand(strtotime("2018-05-01"),strtotime("2018-06-30"))),
			],
			[
				'proj_id' => 1,
				'user_id' => 1,
				'proc_id' => 11,
				'mat_id' => 1,
				'pp_id'	=> 2,
				'prog_remark' => 'Material has moved to the marking subprocess by PPC 1',
				'created_at' => date("Y-m-d H:i:s", mt_rand(strtotime("2018-05-01"),strtotime("2018-06-30"))),
			],
			[
				'proj_id' => 1,
				'user_id' => 1,
				'proc_id' => 11,
				'mat_id' => 1,
				'pp_id'	=> 3,
				'prog_remark' => 'Material has moved to the marking subprocess by PPC 1',
				'created_at' => date("Y-m-d H:i:s", mt_rand(strtotime("2018-05-01"),strtotime("2018-06-30"))),
			],
			[
				'proj_id' => 1,
				'user_id' => 1,
				'proc_id' => 11,
				'mat_id' => 2,
				'pp_id'	=> 4,
				'prog_remark' => 'Material has moved to the marking subprocess by PPC 1',
				'created_at' => date("Y-m-d H:i:s", mt_rand(strtotime("2018-05-01"),strtotime("2018-06-30"))),
			],
			[
				'proj_id' => 1,
				'user_id' => 1,
				'proc_id' => 11,
				'mat_id' => 2,
				'pp_id'	=> 5,
				'prog_remark' => 'Material has moved to the marking subprocess by PPC 1',
				'created_at' => date("Y-m-d H:i:s", mt_rand(strtotime("2018-05-01"),strtotime("2018-06-30"))),
			],
			[
				'proj_id' => 1,
				'user_id' => 1,
				'proc_id' => 11,
				'mat_id' => 3,
				'pp_id'	=> 6,
				'prog_remark' => 'Material has moved to the marking subprocess by PPC 1',
				'created_at' => date("Y-m-d H:i:s", mt_rand(strtotime("2018-05-01"),strtotime("2018-06-30"))),
			],
			[
				'proj_id' => 1,
				'user_id' => 1,
				'proc_id' => 11,
				'mat_id' => 3,
				'pp_id'	=> 7,
				'prog_remark' => 'Material has moved to the marking subprocess by PPC 1',
				'created_at' => date("Y-m-d H:i:s", mt_rand(strtotime("2018-05-01"),strtotime("2018-06-30"))),
			],
			[
				'proj_id' => 1,
				'user_id' => 1,
				'proc_id' => 12,
				'mat_id' => 1,
				'pp_id'	=> 1,
				'prog_remark' => 'Material has moved to the cutting subprocess by PPC 1',
				'created_at' => date("Y-m-d H:i:s", mt_rand(strtotime("2018-05-01"),strtotime("2018-06-30"))),
			],
			[
				'proj_id' => 1,
				'user_id' => 1,
				'proc_id' => 12,
				'mat_id' => 1,
				'pp_id'	=> 2,
				'prog_remark' => 'Material has moved to the cutting subprocess by PPC 1',
				'created_at' => date("Y-m-d H:i:s", mt_rand(strtotime("2018-05-01"),strtotime("2018-06-30"))),
			],
			[
				'proj_id' => 1,
				'user_id' => 1,
				'proc_id' => 12,
				'mat_id' => 1,
				'pp_id'	=> 3,
				'prog_remark' => 'Material has moved to the cutting subprocess by PPC 1',
				'created_at' => date("Y-m-d H:i:s", mt_rand(strtotime("2018-05-01"),strtotime("2018-06-30"))),
			],
			[
				'proj_id' => 1,
				'user_id' => 1,
				'proc_id' => 12,
				'mat_id' => 2,
				'pp_id'	=> 4,
				'prog_remark' => 'Material has moved to the cutting subprocess by PPC 1',
				'created_at' => date("Y-m-d H:i:s", mt_rand(strtotime("2018-05-01"),strtotime("2018-06-30"))),
			],
			[
				'proj_id' => 1,
				'user_id' => 1,
				'proc_id' => 12,
				'mat_id' => 2,
				'pp_id'	=> 5,
				'prog_remark' => 'Material has moved to the cutting subprocess by PPC 1',
				'created_at' => date("Y-m-d H:i:s", mt_rand(strtotime("2018-05-01"),strtotime("2018-06-30"))),
			],
			[
				'proj_id' => 1,
				'user_id' => 1,
				'proc_id' => 12,
				'mat_id' => 3,
				'pp_id'	=> 6,
				'prog_remark' => 'Material has moved to the cutting subprocess by PPC 1',
				'created_at' => date("Y-m-d H:i:s", mt_rand(strtotime("2018-05-01"),strtotime("2018-06-30"))),
			],
			[
				'proj_id' => 1,
				'user_id' => 1,
				'proc_id' => 12,
				'mat_id' => 3,
				'pp_id'	=> 7,
				'prog_remark' => 'Material has moved to the cutting subprocess by PPC 1',
				'created_at' => date("Y-m-d H:i:s", mt_rand(strtotime("2018-05-01"),strtotime("2018-06-30"))),
			],
			[
				'proj_id' => 1,
				'user_id' => 1,
				'proc_id' => 13,
				'mat_id' => 1,
				'pp_id'	=> 1,
				'prog_remark' => 'Material has moved to the bending subprocess by PPC 1',
				'created_at' => date("Y-m-d H:i:s", mt_rand(strtotime("2018-05-01"),strtotime("2018-06-30"))),
			],
			[
				'proj_id' => 1,
				'user_id' => 1,
				'proc_id' => 13,
				'mat_id' => 1,
				'pp_id'	=> 2,
				'prog_remark' => 'Material has moved to the bending subprocess by PPC 1',
				'created_at' => date("Y-m-d H:i:s", mt_rand(strtotime("2018-05-01"),strtotime("2018-06-30"))),
			],
			[
				'proj_id' => 1,
				'user_id' => 1,
				'proc_id' => 13,
				'mat_id' => 1,
				'pp_id'	=> 3,
				'prog_remark' => 'Material has moved to the bending subprocess by PPC 1',
				'created_at' => date("Y-m-d H:i:s", mt_rand(strtotime("2018-05-01"),strtotime("2018-06-30"))),
			],
			[
				'proj_id' => 1,
				'user_id' => 1,
				'proc_id' => 13,
				'mat_id' => 2,
				'pp_id'	=> 4,
				'prog_remark' => 'Material has moved to the bending subprocess by PPC 1',
				'created_at' => date("Y-m-d H:i:s", mt_rand(strtotime("2018-05-01"),strtotime("2018-06-30"))),
			],
			[
				'proj_id' => 1,
				'user_id' => 1,
				'proc_id' => 13,
				'mat_id' => 2,
				'pp_id'	=> 5,
				'prog_remark' => 'Material has moved to the bending subprocess by PPC 1',
				'created_at' => date("Y-m-d H:i:s", mt_rand(strtotime("2018-05-01"),strtotime("2018-06-30"))),
			],
			[
				'proj_id' => 1,
				'user_id' => 1,
				'proc_id' => 13,
				'mat_id' => 3,
				'pp_id'	=> 6,
				'prog_remark' => 'Material has moved to the bending subprocess by PPC 1',
				'created_at' => date("Y-m-d H:i:s", mt_rand(strtotime("2018-05-01"),strtotime("2018-06-30"))),
			],
			[
				'proj_id' => 1,
				'user_id' => 1,
				'proc_id' => 13,
				'mat_id' => 3,
				'pp_id'	=> 7,
				'prog_remark' => 'Material has moved to the bending subprocess by PPC 1',
				'created_at' => date("Y-m-d H:i:s", mt_rand(strtotime("2018-05-01"),strtotime("2018-06-30"))),
			],
			[
				'proj_id' => 1,
				'user_id' => 1,
				'proc_id' => 10,
				'mat_id' => 4,
				'pp_id'	=> 8,
				'prog_remark' => 'Material has moved to the Fabrication process by PPC 1',
				'created_at' => date("Y-m-d H:i:s", mt_rand(strtotime("2018-05-01"),strtotime("2018-06-30"))),
			],
			[
				'proj_id' => 1,
				'user_id' => 1,
				'proc_id' => 13,
				'mat_id' => 4,
				'pp_id'	=> 8,
				'prog_remark' => 'Material has moved to the bending subprocess by PPC 1',
				'created_at' => date("Y-m-d H:i:s", mt_rand(strtotime("2018-05-01"),strtotime("2018-06-30"))),
			],
		]);
	}
}
